"""
Title: Emergent Structure Without Conservation

Description:
This script demonstrates a minimal dynamical system that:
- Assumes no conserved quantities
- Has no predefined "entities"
- Uses only:
    - State evolution
    - Observables (functions over state)
    - Selection criteria (predictability, persistence)

We show how "entities" and "flows" emerge from:
    dynamics + observables + thresholds

This operationalizes the conceptual framework discussed:
    - No substances
    - No conservation laws
    - Structure emerges from dynamics

Author: Generated by ChatGPT
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN


# -----------------------------
# 1. DEFINE DYNAMICAL SYSTEM
# -----------------------------
def initialize_system(dim=5, seed=42):
    """
    Initializes a random dynamical system.

    Parameters:
        dim (int): Dimension of state space
        seed (int): Random seed for reproducibility

    Returns:
        A (ndarray): Random transformation matrix
    """
    np.random.seed(seed)
    A = np.random.randn(dim, dim) * 0.5
    return A


def evolve_system(A, x0, steps=500, noise_scale=0.1):
    """
    Evolves the system over time.

    Dynamics:
        x_{t+1} = tanh(A x_t) + noise

    No conserved quantities are assumed.

    Returns:
        trajectory (ndarray): shape (steps, dim)
    """
    dim = len(x0)
    trajectory = np.zeros((steps, dim))
    x = x0.copy()

    for t in range(steps):
        noise = np.random.randn(dim) * noise_scale
        x = np.tanh(A @ x) + noise
        trajectory[t] = x

    return trajectory


# -----------------------------
# 2. DEFINE OBSERVABLES
# -----------------------------
def observables(x):
    """
    Define multiple observables (no ontological commitment).

    Each observable is just a function over the state.

    Returns:
        vector of observable values
    """
    return np.array([
        x[0],                 # projection
        np.linalg.norm(x),    # magnitude
        x[0] * x[1],         # interaction
    ])


def compute_observable_trajectory(trajectory):
    """
    Applies observables to trajectory.

    Returns:
        observable_trajectory (ndarray)
    """
    return np.array([observables(x) for x in trajectory])


# -----------------------------
# 3. STRUCTURE DETECTION
# -----------------------------
def cluster_observables(obs_traj):
    """
    Identify "entities" as clusters in observable space.

    No predefined entities — clusters emerge from data.
    """
    clustering = DBSCAN(eps=0.5, min_samples=10).fit(obs_traj)
    return clustering.labels_


# -----------------------------
# 4. PLOT RESULTS
# -----------------------------
def plot_results(obs_traj, labels):
    """
    Visualizes emergent structure.

    Clusters represent emergent "entities"
    """
    plt.figure(figsize=(8,6))
    scatter = plt.scatter(obs_traj[:,0], obs_traj[:,1], c=labels, cmap='viridis', s=10)
    plt.xlabel("Observable 1")
    plt.ylabel("Observable 2")
    plt.title("Emergent Structure (No Conservation, No Substance)")
    plt.colorbar(scatter)
    plt.show()


# -----------------------------
# 5. MAIN EXECUTION
# -----------------------------
def main():
    """
    Full pipeline:
    1. Generate dynamics
    2. Define observables
    3. Extract structure
    4. Visualize emergent entities
    """
    dim = 5
    A = initialize_system(dim)
    x0 = np.random.randn(dim)

    trajectory = evolve_system(A, x0)
    obs_traj = compute_observable_trajectory(trajectory)

    labels = cluster_observables(obs_traj)

    plot_results(obs_traj, labels)


if __name__ == "__main__":
    main()
